# Generated by Django 5.2.7 on 2025-10-11 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('breed', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('suburb', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(choices=[('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('SA', 'SA'), ('WA', 'WA'), ('TAS', 'TAS'), ('ACT', 'ACT'), ('NT', 'NT')], default='NSW', max_length=3)),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=9)),
                ('adoption_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('address_line', models.CharField(blank=True, max_length=120)),
                ('suburb', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(choices=[('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('SA', 'SA'), ('WA', 'WA'), ('TAS', 'TAS'), ('ACT', 'ACT'), ('NT', 'NT')], default='NSW', max_length=3)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('dwelling_ownership', models.CharField(blank=True, max_length=40)),
                ('dwelling_type', models.CharField(blank=True, max_length=40)),
                ('yard_size', models.CharField(blank=True, max_length=40)),
                ('children', models.CharField(blank=True, max_length=40)),
                ('other_pets', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_reason', models.TextField()),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_apps', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_apps', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hiking.animal')),
            ],
            options={
                'unique_together': {('animal', 'adopter')},
            },
        ),
    ]
