# Generated by Django 5.2.7 on 2025-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
    ]

    operations = [
    migrations.RenameField(
        model_name="adoptionapplication",
        old_name="application_reason",
        new_name="reason",
    ),
]
