# Generated by Django 5.2.7 on 2025-10-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0002_remove_adoptionapplication_application_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
